DROP DATABASE IF EXISTS sector1;
CREATE DATABASE IF NOT EXISTS sector1;
USE sector1;
-- Div
DROP TABLE IF EXISTS base _confidencial;
CREATE TABLE IF NOT EXISTS base _confidencial(
    id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    cod_Predio INT NOT NULL,

    coluna_confidencial
    ...

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
